
$FL = "%{fn}@%{dn}
%{ln}@%{dn}
%{fn}%{ln}@%{dn}
%{fn}.%{ln}@%{dn}
%{fi}%{ln}@%{dn}
%{fi}.%{ln}@%{dn}
%{fn}%{li}@%{dn}
%{fn}.%{li}@%{dn}
%{fi}%{li}@%{dn}
%{fi}.%{li}@%{dn}
%{ln}%{fn}@%{dn}
%{ln}.%{fn}@%{dn}
%{ln}%{fi}@%{dn}
%{ln}.%{fi}@%{dn}
%{li}%{fn}@%{dn}
%{li}.%{fn}@%{dn}
%{li}%{fi}@%{dn}
%{li}.%{fi}@%{dn}
%{fn}-%{ln}@%{dn}
%{fi}-%{ln}@%{dn}
%{fn}-%{li}@%{dn}
%{fi}-%{li}@%{dn}
%{ln}-%{fn}@%{dn}
%{ln}-%{fi}@%{dn}
%{li}-%{fn}@%{dn}
%{li}-%{fi}@%{dn}
%{fn}_%{ln}@%{dn}
%{fi}_%{ln}@%{dn}
%{fn}_%{li}@%{dn}
%{fi}_%{li}@%{dn}
%{ln}_%{fn}@%{dn}
%{ln}_%{fi}@%{dn}
%{li}_%{fn}@%{dn}
%{li}_%{fi}@%{dn}
"

$FML = "%{fn}@%{dn}
%{ln}@%{dn}
%{fn}%{ln}@%{dn}
%{fn}.%{ln}@%{dn}
%{fi}%{ln}@%{dn}
%{fi}.%{ln}@%{dn}
%{fn}%{li}@%{dn}
%{fn}.%{li}@%{dn}
%{fi}%{li}@%{dn}
%{fi}.%{li}@%{dn}
%{ln}%{fn}@%{dn}
%{ln}.%{fn}@%{dn}
%{ln}%{fi}@%{dn}
%{ln}.%{fi}@%{dn}
%{li}%{fn}@%{dn}
%{li}.%{fn}@%{dn}
%{li}%{fi}@%{dn}
%{li}.%{fi}@%{dn}
%{fi}%{mi}%{ln}@%{dn}
%{fi}%{mi}.%{ln}@%{dn}
%{fn}%{mi}%{ln}@%{dn}
%{fn}.%{mi}.%{ln}@%{dn}
%{fn}%{mn}%{ln}@%{dn}
%{fn}.%{mn}.%{ln}@%{dn}
%{fn}-%{ln}@%{dn}
%{fi}-%{ln}@%{dn}
%{fn}-%{li}@%{dn}
%{fi}-%{li}@%{dn}
%{ln}-%{fn}@%{dn}
%{ln}-%{fi}@%{dn}
%{li}-%{fn}@%{dn}
%{li}-%{fi}@%{dn}
%{fi}%{mi}-%{ln}@%{dn}
%{fn}-%{mi}-%{ln}@%{dn}
%{fn}-%{mn}-%{ln}@%{dn}
%{fn}_%{ln}@%{dn}
%{fi}_%{ln}@%{dn}
%{fn}_%{li}@%{dn}
%{fi}_%{li}@%{dn}
%{ln}_%{fn}@%{dn}
%{ln}_%{fi}@%{dn}
%{li}_%{fn}@%{dn}
%{li}_%{fi}@%{dn}
%{fi}%{mi}_%{ln}@%{dn}
%{fn}_%{mi}_%{ln}@%{dn}
%{fn}_%{mn}_%{ln}@%{dn}
%{mn}@%{dn}
"
